### ISSUE TITLE
Config::AutoConf::INI

### ISSUE THREAD

**Issue by jddurand** [ambs/Config-AutoConf#12]
Hello,

This is not an issue but a question, thoug I do not know how to do a "question" via github interface -;

I have writen a tiny helper module around Config::AutoConf: [Config::AutoConf::INI](https://github.com/jddurand/perl-Config-AutoConf-INI) - and would like to know if this is okay for you that I abuse the Config::AutoConf namespace before pushing to CPAN - no problem for me to rename it;

Many thanks.

**Comment by ambs** [comment]
No problem. Go ahead :)
Best!
