### ISSUE TITLE
[PRC] How may I be of help

### ISSUE THREAD

**Issue by JJ** [ambs/Config-AutoConf#15]
I've been assigned this module for August Pull Request challenge. How would you like me to help?

**Comment by rehsack** [comment]
Hey @JJ - that heavily depends on your available time.

The Long-Term goal is heaving all information in local variable hash to run a thing like ()(Makefile.in) -> (Makefile) as perl6 (MoarVM, NQP, Rakudo*) are doing.

It would help dramatically, if there would be an abstraction layer for doing compile jobs to avoid the ExtUtils::CBuilder dependency (
https://github.com/ambs/Config-AutoConf/issues/6) and can prove for CXX, FORTRAN, JAVAC, GO, ... too.
Also, distinguishing between HOST_CC, BUILD_CC and TARGET_CC ... would be nice.

Please see https://www.lrde.epita.fr/~adl/dl/autotools.pdf and 
http://www.netbsd.org/~sno/talks/tpc2017/Cross-Compiling-For-Perl-Hackers-Handout.pdf for some background information.

OTOH, if you're lurking for a small goal, please checkout 
https://github.com/ambs/Config-AutoConf/issues/11

**Comment by JJ** [comment]
Finally, I'm over the deadline and I don't have a lot of time for this. I have checked out #11 and I can't really figure it out; not clear if you want another function, or to use the environment variables of that value.
